SYSTEM:
  EXP_NAME: 'permute-er'
  SEED: 43
  LOG_FREQ: 100
DATA:
  TRAIN:
    ROOT: './torch_data/mnist/permute/train.pt'
    NUM_SAMPLES: 1000
  TEST:
    ROOT: './torch_data/mnist/permute/test.pt'
SOLVER:
  NUM_TASKS: 10
  BATCH_SIZE: 10
  NUM_EPOCHS: 1
OPTIMIZER:
  LR: 0.05
  MOMENTUM: 0.00
BUFFER:
  SIZE: 500
  C: 10
