SYSTEM:
  EXP_NAME: 'permute-er-mir'
  SEED: 43
  LOG_FREQ: 10
DATA:
  TRAIN:
    ROOT: './torch_data/mnist/permute/train.pt'
    NUM_SAMPLES: 1000
  TEST:
    ROOT: './torch_data/mnist/permute/test.pt'
SOLVER:
  NUM_TASKS: 5
  BATCH_SIZE: 10
  NUM_EPOCHS: 1
  SAMPLING_CRITERION: 1
OPTIMIZER:
  LR: 0.05
  MOMENTUM: 0.09
BUFFER:
  SIZE: 500
  C: 50
