SYSTEM:
  EXP_NAME: 'permute-fine-tuning'
DATA:
  TRAIN:
    ROOT: './torch_data/mnist/permute/train.pt'
  TEST:
    ROOT: './torch_data/mnist/permute/test.pt'
SOLVER:
  NUM_TASKS: 10
OPTIMIZER:
  LR: 0.05
  MOMENTUM: 0.09
