SYSTEM:
  EXP_NAME: 'split-er-mir'
  SEED: 43
  LOG_FREQ: 100
SOLVER:
  NUM_TASKS: 5
  BATCH_SIZE: 10
  NUM_EPOCHS: 1
  BUDGET: 10
  SAMPLING_CRITERION: 1
OPTIMIZER:
  LR: 0.05
  MOMENTUM: 0.09
BUFFER:
  SIZE: 500
  C: 10
