SYSTEM:
  EXP_NAME: 'split-er'
  SEED: 43
  LOG_FREQ: 10
DATA:
  TRAIN:
    NUM_SAMPLES: 1000
  TEST:
    NUM_SAMPLES: 1000
SOLVER:
  NUM_TASKS: 5
  BATCH_SIZE: 10
  NUM_EPOCHS: 1
OPTIMIZER:
  LR: 0.05
  MOMENTUM: 0.09
BUFFER:
  SIZE: 500
  C: 10
