SYSTEM:
  EXP_NAME: 'cifar-er-mir'
  SEED: 43
  LOG_FREQ: 10
DATA:
  TYPE: 'cifar'
  TRAIN:
    ROOT: './torch_data/cifar10/train.pt'
    NUM_SAMPLES: 9750
  TEST:
    ROOT: './torch_data/cifar10/test.pt'
    NUM_SAMPLES: 9750
SOLVER:
  NUM_TASKS: 5
  BATCH_SIZE: 50
  NUM_EPOCHS: 1
  SAMPLING_CRITERION: 1
OPTIMIZER:
  LR: 0.1
  MOMENTUM: 0.0
BUFFER:
  SIZE: 500
  C: 50
